export enum ErrorCode {
  API_FETCH_ERROR = "API_FETCH_ERROR",
  API_TIMEOUT = "API_TIMEOUT",
  API_NETWORK_ERROR = "API_NETWORK_ERROR",
  CART_LOAD_ERROR = "CART_LOAD_ERROR",
  CART_SAVE_ERROR = "CART_SAVE_ERROR",
  CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND",
  CART_INVALID_QUANTITY = "CART_INVALID_QUANTITY",
  STORAGE_READ_ERROR = "STORAGE_READ_ERROR",
  STORAGE_WRITE_ERROR = "STORAGE_WRITE_ERROR",
  STORAGE_QUOTA_EXCEEDED = "STORAGE_QUOTA_EXCEEDED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_INPUT = "INVALID_INPUT",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_LOAD_ERROR = "PRODUCT_LOAD_ERROR",
  CHECKOUT_VALIDATION_ERROR = "CHECKOUT_VALIDATION_ERROR",
  CHECKOUT_SUBMIT_ERROR = "CHECKOUT_SUBMIT_ERROR",
  FAVORITES_LOAD_ERROR = "FAVORITES_LOAD_ERROR",
  FAVORITES_SAVE_ERROR = "FAVORITES_SAVE_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

export interface ErrorContext {
  [key: string]: unknown;
}

